benchmark: "blackscholes"
benchmark_size: "simlarge"
# cr3filepath: "/home/dorian/thesis/thesis/qemu/cr3_output"
# crvaluespath: "/home/dorian/thesis/thesis/crvalues"
# pgtabledumppath: "/media/ssd/pgtable_dump"
memory_dump_path: "/home/dorian/thesis"
cachesimulator:
  run: true
  path: "/home/dorian/go/src/github.com/doriandekoning/functional-cache-simulator/bin/simple"
  distributed: false
  output: "/media/ssd/cachesimout"
qemu:
  run: true
  path: "/home/dorian/thesis/qemutracingphysmem/qemu/build/x86_64-softmmu/qemu-system-x86_64"
  drive: "/media/ssd/disks/parsec_disposable.img"
  kernel: "/home/dorian/thesis/linux-5.0/arch/x86_64/boot/bzImage"
  events: "/home/dorian/thesis/thesis/qemu/cr3event"
  # trace: "/home/dorian/go/src/github.com/doriandekoning/run-qemu-cache-distributed-sim/pipe"
  trace: "/media/ssd/sometesttrace"
  num_cores: 2
  trace_mapping_out: "/home/dorian/go/src/github.com/doriandekoning/run-qemu-cache-distributed-sim/trace_mapping_use"
#  trace: "/dev/null"
