usepipe: true
benchmark: "blackscholes"
benchmark_size: "simlarge"
cr3filepath: "/home/dorian/thesis/thesis/qemu/cr3_output"
crvaluespath: "/home/dorian/thesis/thesis/crvalues"
pgtabledumppath: "/media/ssd/pgtable_dump"
cachesimulator:
  run: false
qemu:
  run: true
  path: "/home/dorian/thesis/qemutracingphysmem/qemu/build/x86_64-softmmu/qemu-system-x86_64"
  drive: "/media/ssd/disks/parsec_disposable.img"
  kernel: "/home/dorian/thesis/linux-5.0/arch/x86_64/boot/bzImage"
#  events: "/home/dorian/thesis/thesis/qemu/cr3event"
#  events:  "/home/dorian/thesis/qemutracingphysmem/qemu/build/trace-events-all"
  events: "/home/dorian/go/src/github.com/doriandekoning/run-qemu-cache-distributed-sim/no_events"
#  events: "/home/dorian/go/src/github.com/doriandekoning/run-qemu-cache-distributed-sim/all_needed_events"
  trace: "/media/ssd/testtrace"
#  trace: "/dev/null"
  num_cores: 2
<<<<<<< Updated upstream
  num_cores: 2
=======
>>>>>>> Stashed changes
  qmp_telnet_port: 4444
